# Generated by Django 4.1.7 on 2023-03-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_profile_delete_user_alter_image_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='parent',
            new_name='parent_name',
        ),
    ]
