# Generated by Django 4.1.7 on 2023-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_original_file_image_original_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/200/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/400/'),
        ),
    ]
