# Generated by Django 4.1.7 on 2023-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_thumbnail_200_image_thumbnail_400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to='img/<built-in function id>'),
        ),
    ]
