# Generated by Django 4.1.7 on 2023-03-09 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0009_alter_image_original_image_alter_image_thumbnail_200_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='MyImage',
        ),
    ]
