# Generated by Django 4.1.7 on 2023-03-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_myimage_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='original_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
