# Generated by Django 4.1.7 on 2023-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_alter_myimage_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='original_image',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='img/thumb_200/'),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='img/thumb_400/'),
        ),
    ]
